spring:
  rabbitmq:
    host: localhost
    virtual-host: vhost
    password: password
    username: user
    port: 5672

grpc:
  client:
    local-grpc-server:
      address: "static://localhost:9090"
      enable-keep-alive: true
