server:
  port: 8099

spring:
  amqp:
    deserialization:
      trust-all: true
  rabbitmq:
    host: localhost
    virtual-host: vhost
    password: password
    username: user

  datasource:
    url: jdbc:clickhouse://localhost:8123/smart_home_logs?compress=0
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
